name: Web - production

on:
  push:
    branches:
      - master
    paths:
      - apps/web/**
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

  lint:
    name: Run lint
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Lint
        run: npm run lint:web

  unit-tests:
    name: Unit Tests
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Test
        run: npm run test
        working-directory: ./apps/web

  deploy:
    name: Deploy
    needs:
      - unit-tests
      - lint

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    env:
      VITE_APP_TITLE: ${{ vars.VITE_APP_TITLE }}
      VITE_EXTENSION_URL: ${{ vars.VITE_EXTENSION_URL }}
      VITE_BUY_ME_A_COFFEE_URL: ${{ vars.VITE_BUY_ME_A_COFFEE_URL }}
      VITE_GITHUB_URL: ${{ vars.VITE_GITHUB_URL}}
      VITE_CHANGELOG_URL: ${{ vars.VITE_CHANGELOG_URL }}
      VITE_PERSONAL_WEBSITE_URL: ${{ vars.VITE_PERSONAL_WEBSITE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: npm run build
        working-directory: ./apps/web

      - name: Upload to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./apps/web/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
