name: Web

on:
  pull_request:
    paths:
      - "apps/web/**"
  workflow_dispatch:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

  install-dependencies:
    name: Install dependencies
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies (from root)
        run: npm install

  lint:
    name: Run lint
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run lint
        working-directory: apps/web

  unit-tests:
    name: Unit Tests
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: npm run test
        working-directory: apps/web

  build:
    name: Build
    needs:
      - init
      - unit-tests

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build
        working-directory: apps/web
