name: Web

on:
  pull_request:
    paths:
      - "apps/web/**"
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install dependencies
    needs: init
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

  lint:
    name: Run lint
    needs:
      - init
      - install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Lint
        run: npm run lint
        working-directory: ./apps/web

  unit-tests:
    name: Unit Tests
    needs:
      - init
      - install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Test
        run: npm run test
        working-directory: ./apps/web

  build:
    name: Build
    needs:
      - init
      - unit-tests
      - lint

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: 24

      - name: Build
        run: npm run build
        working-directory: ./apps/web
