name: Web

on:
  pull_request:
    paths:
      - "apps/extension/**"
  push:
    paths:
      - "apps/extension/**"
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies (from root)
        run: npm install

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run lint
        working-directory: apps/extension

    tests:
      runs-on: ubuntu-latest

      steps:
        - name: Test
          run: npm run test
          working-directory: apps/extension

    build:
      runs-on: ubuntu-latest

      steps:
        - name: Build
          run: npm run build
          working-directory: apps/extension
